/**
 * Email i18n catalog.
 *
 * Email templates pull every user-facing string from here. `t()` falls back
 * to English for any key a locale is missing, so partial translations never
 * render a broken email — and adding a locale means adding one catalog entry.
 *
 * For now `en` is complete and every locale translates the shared chrome
 * (footer, common labels); template-specific keys fall back to English until
 * fully translated.
 */

export const EMAIL_LOCALES = [
  "en",
  "es",
  "fr",
  "de",
  "pt-BR",
  "ja",
  "ko",
  "zh-CN",
  "ar",
] as const;

export type EmailLocale = (typeof EMAIL_LOCALES)[number];

type Dict = Record<string, string>;

const en: Dict = {
  // Footer chrome
  "footer.dashboard": "Dashboard",
  "footer.status": "Status",
  "footer.docs": "Docs",
  "footer.preferences": "Preferences",
  "footer.tagline": "SteadyStack Edge Telemetry & Real-Time Observability Engine",
  "footer.secured": "Secured with 256-bit distributed consensus",
  // Alert template
  "alert.critical": "CRITICAL ALERT",
  "alert.degraded": "REGIONAL DEGRADATION",
  "alert.resolved": "INCIDENT RESOLVED",
  "alert.sslWarning": "SSL WARNING",
  "alert.outageTitle": "Service Outage Detected",
  "alert.degradedTitle": "Partial Regional Failure Detected",
  "alert.recoveredTitle": "Service Recovered & Operational",
  "alert.sslTitle": "SSL Certificate Expiring Soon",
  "alert.serviceDown": "SERVICE DOWN",
  "alert.expiryNotice": "EXPIRY NOTICE",
  "alert.serviceRestored": "SERVICE RESTORED",
  "alert.statusChange": "Status Change:",
  "alert.timestamp": "Timestamp:",
  "alert.totalDowntime": "Total Downtime:",
  "alert.failureReason": "Failure Reason:",
  "alert.detectedFrom": "Detected from {count} Edge Locations:",
  "alert.viewRunbook": "View Incident Runbook",
  "alert.investigate": "Investigate Incident",
  "alert.viewTelemetry": "View Live Telemetry",
  "alert.orOpen": "Or open",
  "alert.monitorDashboard": "monitor dashboard",
  "alert.autoMessage":
    "This is an automated alert generated by the SteadyStack edge consensus engine.",
  // Status update template
  "status.statusUpdateSuffix": "Status Update",
  "status.statusLabel": "STATUS:",
  "status.affectedComponents": "Affected Components:",
  "status.viewLiveStatus": "View Live Status Page",
  "status.subscribedMessage":
    "You are receiving this because you subscribed to status updates for {page}.",
};

const es: Dict = {
  "footer.dashboard": "Panel",
  "footer.status": "Estado",
  "footer.docs": "Documentación",
  "footer.preferences": "Preferencias",
  "footer.tagline": "Motor de telemetría de borde y observabilidad en tiempo real de SteadyStack",
  "footer.secured": "Protegido con consenso distribuido de 256 bits",
  "alert.critical": "ALERTA CRÍTICA",
  "alert.degraded": "DEGRADACIÓN REGIONAL",
  "alert.resolved": "INCIDENTE RESUELTO",
  "alert.sslWarning": "ADVERTENCIA SSL",
  "alert.outageTitle": "Interrupción del servicio detectada",
  "alert.degradedTitle": "Falla regional parcial detectada",
  "alert.recoveredTitle": "Servicio recuperado y operativo",
  "alert.sslTitle": "El certificado SSL expirará pronto",
  "alert.serviceDown": "SERVICIO CAÍDO",
  "alert.expiryNotice": "AVISO DE EXPIRACIÓN",
  "alert.serviceRestored": "SERVICIO RESTAURADO",
  "alert.statusChange": "Cambio de estado:",
  "alert.timestamp": "Fecha y hora:",
  "alert.totalDowntime": "Tiempo total de inactividad:",
  "alert.failureReason": "Motivo del fallo:",
  "alert.detectedFrom": "Detectado desde {count} ubicaciones de borde:",
  "alert.viewRunbook": "Ver manual del incidente",
  "alert.investigate": "Investigar incidente",
  "alert.viewTelemetry": "Ver telemetría en vivo",
  "alert.orOpen": "O abre",
  "alert.monitorDashboard": "el panel del monitor",
  "alert.autoMessage":
    "Esta es una alerta automática generada por el motor de consenso de borde de SteadyStack.",
  "status.statusUpdateSuffix": "Actualización de estado",
  "status.statusLabel": "ESTADO:",
  "status.affectedComponents": "Componentes afectados:",
  "status.viewLiveStatus": "Ver página de estado en vivo",
  "status.subscribedMessage":
    "Recibes esto porque te suscribiste a las actualizaciones de estado de {page}.",
};

const fr: Dict = {
  "footer.dashboard": "Tableau de bord",
  "footer.status": "Statut",
  "footer.docs": "Documentation",
  "footer.preferences": "Préférences",
  "footer.tagline": "Moteur de télémétrie de périphérie et d'observabilité en temps réel SteadyStack",
  "footer.secured": "Sécurisé par consensus distribué 256 bits",
  "alert.critical": "ALERTE CRITIQUE",
  "alert.degraded": "DÉGRADATION RÉGIONALE",
  "alert.resolved": "INCIDENT RÉSOLU",
  "alert.sslWarning": "AVERTISSEMENT SSL",
  "alert.outageTitle": "Panne de service détectée",
  "alert.degradedTitle": "Défaillance régionale partielle détectée",
  "alert.recoveredTitle": "Service rétabli et opérationnel",
  "alert.sslTitle": "Le certificat SSL expire bientôt",
  "alert.serviceDown": "SERVICE HORS LIGNE",
  "alert.expiryNotice": "AVIS D'EXPIRATION",
  "alert.serviceRestored": "SERVICE RÉTABLI",
  "alert.statusChange": "Changement d'état :",
  "alert.timestamp": "Horodatage :",
  "alert.totalDowntime": "Temps d'indisponibilité total :",
  "alert.failureReason": "Cause de l'échec :",
  "alert.detectedFrom": "Détecté depuis {count} sites de périphérie :",
  "alert.viewRunbook": "Voir le guide d'incident",
  "alert.investigate": "Enquêter sur l'incident",
  "alert.viewTelemetry": "Voir la télémétrie en direct",
  "alert.orOpen": "Ou ouvrez",
  "alert.monitorDashboard": "le tableau de bord du moniteur",
  "alert.autoMessage":
    "Ceci est une alerte automatique générée par le moteur de consensus de périphérie SteadyStack.",
  "status.statusUpdateSuffix": "Mise à jour de statut",
  "status.statusLabel": "STATUT :",
  "status.affectedComponents": "Composants concernés :",
  "status.viewLiveStatus": "Voir la page de statut en direct",
  "status.subscribedMessage":
    "Vous recevez ceci car vous vous êtes abonné aux mises à jour de statut de {page}.",
};

const de: Dict = {
  "footer.dashboard": "Dashboard",
  "footer.status": "Status",
  "footer.docs": "Dokumentation",
  "footer.preferences": "Einstellungen",
  "footer.tagline": "SteadyStack Edge-Telemetrie- und Echtzeit-Observability-Engine",
  "footer.secured": "Gesichert mit verteiltem 256-Bit-Konsens",
  "alert.critical": "KRITISCHE WARNUNG",
  "alert.degraded": "REGIONALE DEGRADATION",
  "alert.resolved": "VORFALL BEHOBEN",
  "alert.sslWarning": "SSL-WARNUNG",
  "alert.outageTitle": "Dienstausfall erkannt",
  "alert.degradedTitle": "Partieller regionaler Ausfall erkannt",
  "alert.recoveredTitle": "Dienst wiederhergestellt und funktionsfähig",
  "alert.sslTitle": "SSL-Zertifikat läuft bald ab",
  "alert.serviceDown": "DIENST AUSGEFALLEN",
  "alert.expiryNotice": "ABLAUFHINWEIS",
  "alert.serviceRestored": "DIENST WIEDERHERGESTELLT",
  "alert.statusChange": "Statusänderung:",
  "alert.timestamp": "Zeitstempel:",
  "alert.totalDowntime": "Gesamte Ausfallzeit:",
  "alert.failureReason": "Fehlerursache:",
  "alert.detectedFrom": "Erkannt von {count} Edge-Standorten:",
  "alert.viewRunbook": "Vorfall-Runbook anzeigen",
  "alert.investigate": "Vorfall untersuchen",
  "alert.viewTelemetry": "Live-Telemetrie anzeigen",
  "alert.orOpen": "Oder öffnen Sie",
  "alert.monitorDashboard": "das Monitor-Dashboard",
  "alert.autoMessage":
    "Dies ist eine automatische Warnung der Edge-Konsens-Engine von SteadyStack.",
  "status.statusUpdateSuffix": "Status-Update",
  "status.statusLabel": "STATUS:",
  "status.affectedComponents": "Betroffene Komponenten:",
  "status.viewLiveStatus": "Live-Statusseite anzeigen",
  "status.subscribedMessage":
    "Sie erhalten diese E-Mail, weil Sie Status-Updates für {page} abonniert haben.",
};

const ptBR: Dict = {
  "footer.dashboard": "Painel",
  "footer.status": "Status",
  "footer.docs": "Documentação",
  "footer.preferences": "Preferências",
  "footer.tagline": "Motor de telemetria de borda e observabilidade em tempo real da SteadyStack",
  "footer.secured": "Protegido com consenso distribuído de 256 bits",
  "alert.critical": "ALERTA CRÍTICO",
  "alert.degraded": "DEGRADAÇÃO REGIONAL",
  "alert.resolved": "INCIDENTE RESOLVIDO",
  "alert.sslWarning": "AVISO DE SSL",
  "alert.outageTitle": "Interrupção de serviço detectada",
  "alert.degradedTitle": "Falha regional parcial detectada",
  "alert.recoveredTitle": "Serviço recuperado e operacional",
  "alert.sslTitle": "Certificado SSL expirando em breve",
  "alert.serviceDown": "SERVIÇO FORA DO AR",
  "alert.expiryNotice": "AVISO DE EXPIRAÇÃO",
  "alert.serviceRestored": "SERVIÇO RESTAURADO",
  "alert.statusChange": "Mudança de status:",
  "alert.timestamp": "Data e hora:",
  "alert.totalDowntime": "Tempo total de inatividade:",
  "alert.failureReason": "Motivo da falha:",
  "alert.detectedFrom": "Detectado a partir de {count} locais de borda:",
  "alert.viewRunbook": "Ver runbook do incidente",
  "alert.investigate": "Investigar incidente",
  "alert.viewTelemetry": "Ver telemetria ao vivo",
  "alert.orOpen": "Ou abra",
  "alert.monitorDashboard": "o painel do monitor",
  "alert.autoMessage":
    "Este é um alerta automático gerado pelo motor de consenso de borda da SteadyStack.",
  "status.statusUpdateSuffix": "Atualização de status",
  "status.statusLabel": "STATUS:",
  "status.affectedComponents": "Componentes afetados:",
  "status.viewLiveStatus": "Ver página de status ao vivo",
  "status.subscribedMessage":
    "Você recebe isto porque assinou as atualizações de status de {page}.",
};

const ja: Dict = {
  "footer.dashboard": "ダッシュボード",
  "footer.status": "ステータス",
  "footer.docs": "ドキュメント",
  "footer.preferences": "設定",
  "footer.tagline": "SteadyStack エッジテレメトリ＆リアルタイム監視エンジン",
  "footer.secured": "256ビット分散コンセンサスで保護",
  "alert.critical": "緊急アラート",
  "alert.degraded": "リージョン性能低下",
  "alert.resolved": "インシデント解決",
  "alert.sslWarning": "SSL 警告",
  "alert.outageTitle": "サービス障害を検出しました",
  "alert.degradedTitle": "一部リージョンで障害を検出しました",
  "alert.recoveredTitle": "サービスが復旧し、正常に動作しています",
  "alert.sslTitle": "SSL 証明書の有効期限が近づいています",
  "alert.serviceDown": "サービス停止",
  "alert.expiryNotice": "期限のお知らせ",
  "alert.serviceRestored": "サービス復旧",
  "alert.statusChange": "ステータス変更：",
  "alert.timestamp": "発生時刻：",
  "alert.totalDowntime": "合計ダウンタイム：",
  "alert.failureReason": "障害の原因：",
  "alert.detectedFrom": "{count} か所のエッジロケーションから検出：",
  "alert.viewRunbook": "インシデントランブックを見る",
  "alert.investigate": "インシデントを調査",
  "alert.viewTelemetry": "ライブテレメトリを見る",
  "alert.orOpen": "または",
  "alert.monitorDashboard": "モニターダッシュボードを開く",
  "alert.autoMessage":
    "このメッセージは SteadyStack エッジコンセンサスエンジンによる自動アラートです。",
  "status.statusUpdateSuffix": "ステータス更新",
  "status.statusLabel": "ステータス：",
  "status.affectedComponents": "影響を受けるコンポーネント：",
  "status.viewLiveStatus": "ステータスページを見る",
  "status.subscribedMessage": "{page} のステータス更新を購読しているため、この通知をお送りしています。",
};

const ko: Dict = {
  "footer.dashboard": "대시보드",
  "footer.status": "상태",
  "footer.docs": "문서",
  "footer.preferences": "환경설정",
  "footer.tagline": "SteadyStack 엣지 텔레메트리 및 실시간 관측 엔진",
  "footer.secured": "256비트 분산 합의로 보호됨",
  "alert.critical": "긴급 알림",
  "alert.degraded": "리전 성능 저하",
  "alert.resolved": "장애 해결",
  "alert.sslWarning": "SSL 경고",
  "alert.outageTitle": "서비스 장애가 감지되었습니다",
  "alert.degradedTitle": "일부 리전에서 장애가 감지되었습니다",
  "alert.recoveredTitle": "서비스가 복구되어 정상 작동 중입니다",
  "alert.sslTitle": "SSL 인증서 만료가 임박했습니다",
  "alert.serviceDown": "서비스 중단",
  "alert.expiryNotice": "만료 안내",
  "alert.serviceRestored": "서비스 복구",
  "alert.statusChange": "상태 변경:",
  "alert.timestamp": "발생 시각:",
  "alert.totalDowntime": "총 다운타임:",
  "alert.failureReason": "장애 원인:",
  "alert.detectedFrom": "{count}개 엣지 로케이션에서 감지:",
  "alert.viewRunbook": "장애 대응 문서 보기",
  "alert.investigate": "장애 조사",
  "alert.viewTelemetry": "실시간 텔레메트리 보기",
  "alert.orOpen": "또는",
  "alert.monitorDashboard": "모니터 대시보드 열기",
  "alert.autoMessage":
    "이 알림은 SteadyStack 엣지 합의 엔진이 자동으로 생성한 것입니다.",
  "status.statusUpdateSuffix": "상태 업데이트",
  "status.statusLabel": "상태:",
  "status.affectedComponents": "영향을 받는 구성 요소:",
  "status.viewLiveStatus": "실시간 상태 페이지 보기",
  "status.subscribedMessage": "{page}의 상태 업데이트를 구독하고 계셔서 이 알림을 보내드립니다.",
};

const zhCN: Dict = {
  "footer.dashboard": "控制台",
  "footer.status": "状态",
  "footer.docs": "文档",
  "footer.preferences": "偏好设置",
  "footer.tagline": "SteadyStack 边缘遥测与实时可观测引擎",
  "footer.secured": "由 256 位分布式共识保护",
  "alert.critical": "严重告警",
  "alert.degraded": "区域性能下降",
  "alert.resolved": "故障已解决",
  "alert.sslWarning": "SSL 警告",
  "alert.outageTitle": "检测到服务中断",
  "alert.degradedTitle": "检测到部分区域故障",
  "alert.recoveredTitle": "服务已恢复并正常运行",
  "alert.sslTitle": "SSL 证书即将过期",
  "alert.serviceDown": "服务宕机",
  "alert.expiryNotice": "到期提醒",
  "alert.serviceRestored": "服务已恢复",
  "alert.statusChange": "状态变更：",
  "alert.timestamp": "发生时间：",
  "alert.totalDowntime": "总宕机时长：",
  "alert.failureReason": "故障原因：",
  "alert.detectedFrom": "从 {count} 个边缘节点检测到：",
  "alert.viewRunbook": "查看故障处理手册",
  "alert.investigate": "调查故障",
  "alert.viewTelemetry": "查看实时遥测",
  "alert.orOpen": "或打开",
  "alert.monitorDashboard": "监控台",
  "alert.autoMessage": "此告警由 SteadyStack 边缘共识引擎自动生成。",
  "status.statusUpdateSuffix": "状态更新",
  "status.statusLabel": "状态：",
  "status.affectedComponents": "受影响的组件：",
  "status.viewLiveStatus": "查看实时状态页",
  "status.subscribedMessage": "您订阅了 {page} 的状态更新，因此收到此通知。",
};

const ar: Dict = {
  "footer.dashboard": "لوحة التحكم",
  "footer.status": "الحالة",
  "footer.docs": "الوثائق",
  "footer.preferences": "التفضيلات",
  "footer.tagline": "محرك القياس عن بعد الطرفي والمراقبة الفورية من SteadyStack",
  "footer.secured": "محمي بإجماع موزّع بـ 256 بت",
  "alert.critical": "تنبيه حرج",
  "alert.degraded": "تدهور إقليمي",
  "alert.resolved": "تم حل الحادث",
  "alert.sslWarning": "تحذير SSL",
  "alert.outageTitle": "تم اكتشاف انقطاع في الخدمة",
  "alert.degradedTitle": "تم اكتشاف عطل إقليمي جزئي",
  "alert.recoveredTitle": "تمت استعادة الخدمة وهي تعمل بشكل طبيعي",
  "alert.sslTitle": "شهادة SSL على وشك الانتهاء",
  "alert.serviceDown": "الخدمة متوقفة",
  "alert.expiryNotice": "إشعار انتهاء الصلاحية",
  "alert.serviceRestored": "تمت استعادة الخدمة",
  "alert.statusChange": "تغيير الحالة:",
  "alert.timestamp": "التاريخ والوقت:",
  "alert.totalDowntime": "إجمالي مدة التوقف:",
  "alert.failureReason": "سبب الفشل:",
  "alert.detectedFrom": "تم الاكتشاف من {count} مواقع طرفية:",
  "alert.viewRunbook": "عرض دليل الحادث",
  "alert.investigate": "التحقيق في الحادث",
  "alert.viewTelemetry": "عرض القياس عن بعد المباشر",
  "alert.orOpen": "أو افتح",
  "alert.monitorDashboard": "لوحة المراقبة",
  "alert.autoMessage": "هذا تنبيه تلقائي تم إنشاؤه بواسطة محرك الإجماع الطرفي من SteadyStack.",
  "status.statusUpdateSuffix": "تحديث الحالة",
  "status.statusLabel": "الحالة:",
  "status.affectedComponents": "المكونات المتأثرة:",
  "status.viewLiveStatus": "عرض صفحة الحالة المباشرة",
  "status.subscribedMessage": "تتلقى هذا لأنك اشتركت في تحديثات الحالة لـ {page}.",
};

const CATALOGS: Record<EmailLocale, Dict> = {
  en,
  es,
  fr,
  de,
  "pt-BR": ptBR,
  ja,
  ko,
  "zh-CN": zhCN,
  ar,
};

const RTL_LOCALES: ReadonlySet<string> = new Set(["ar"]);

export function isRtlEmailLocale(locale: string): boolean {
  return RTL_LOCALES.has(locale);
}

export function isEmailLocale(locale: string): locale is EmailLocale {
  return (EMAIL_LOCALES as readonly string[]).includes(locale);
}

/** Normalize an arbitrary locale tag (e.g. "pt", "zh-Hans") to a supported one. */
export function normalizeEmailLocale(locale: string | undefined | null): EmailLocale {
  if (!locale) return "en";
  if (isEmailLocale(locale)) return locale;
  const base = locale.split("-")[0]?.toLowerCase() ?? "";
  const match = EMAIL_LOCALES.find((l) => l.toLowerCase().startsWith(base));
  if (match) return match as EmailLocale;
  // Special-case base codes that only map via full tags
  if (base === "pt") return "pt-BR";
  if (base === "zh") return "zh-CN";
  return "en";
}

/** Translate a key with {placeholder} interpolation; falls back to English. */
export function t(
  locale: EmailLocale,
  key: string,
  params: Record<string, string | number> = {},
): string {
  const dict = CATALOGS[locale] ?? en;
  let str = dict[key] ?? en[key] ?? key;
  for (const [name, value] of Object.entries(params)) {
    str = str.replaceAll(`{${name}}`, String(value));
  }
  return str;
}

/**
 * Locale-aware formatter for timestamps inside emails. Emails are static
 * artifacts, so we format once server-side with an explicit timeZone
 * (UTC) instead of relying on the reader's device.
 */
export function formatEmailTimestamp(locale: EmailLocale, date: Date | string): string {
  const d = typeof date === "string" ? new Date(date) : date;
  try {
    return d.toLocaleString(locale === "en" ? "en-US" : locale, {
      dateStyle: "medium",
      timeStyle: "short",
      timeZone: "UTC",
    });
  } catch {
    return d.toUTCString();
  }
}
