version: 2
before:
  hooks:
    - go mod tidy

builds:
  - id: terraform-provider-steadystack
    dir: packages/terraform-provider
    binary: terraform-provider-steadystack_v{{ .Version }}
    flags:
      - -trimpath
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}}
    goos:
      - darwin
      - freebsd
      - linux
      - windows
    goarch:
      - amd64
      - arm
      - arm64
    ignore:
      - goos: darwin
        goarch: arm

archives:
  - id: terraform-provider-steadystack
    format: zip
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - packages/terraform-provider/README.md
      - LICENSE

checksum:
  name_template: "{{ .ProjectName }}_{{ .Version }}_SHA256SUMS"
  algorithm: sha256

signs:
  - artifacts: checksum
    args:
      - "--batch"
      - "--local-user"
      - "{{ .Env.GPG_FINGERPRINT }}"
      - "--output"
      - "${signature}"
      - "--detach-sign"
      - "${artifact}"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
